SELECT
    ir.CD_IT_REPASSE,
    ir.CD_REPASSE,
    ir.CD_REG_AMB,
    ir.CD_LANCAMENTO_AMB,
    ir.CD_REG_FAT,
    ir.CD_LANCAMENTO_FAT,
    ir.CD_ATI_MED,
    ir.CD_PRESTADOR_REPASSE,
    ir.VL_REPASSE
FROM DBAMV.IT_REPASSE ir
WHERE ir.CD_REPASSE >= :PARAM