SELECT
    ia.CD_PRO_FAT,
    ia.CD_REG_AMB,
    ia.CD_PRESTADOR,
    ia.CD_ATI_MED,
    ia.CD_LANCAMENTO,
    ia.CD_GRU_FAT,
    ia.CD_CONVENIO,
    ia.CD_ATENDIMENTO,
    ia.DT_PRODUCAO,
    ia.DT_FECHAMENTO,
    ia.HR_LANCAMENTO AS DT_ITREG_AMB,
    ia.SN_FECHADA,
    ia.SN_REPASSADO,
    ia.SN_PERTENCE_PACOTE,
    ia.VL_UNITARIO,
    ia.VL_TOTAL_CONTA,
    ia.VL_BASE_REPASSADO
FROM DBAMV.ITREG_AMB ia
WHERE (ia.SN_REPASSADO IN ('S', 'N') OR ia.SN_REPASSADO IS NULL) AND ia.HR_LANCAMENTO >= ADD_MONTHS(TRUNC(TO_DATE( ':PARAM' , 'YYYY-MM-DD')), -6)