SELECT
    itf.CD_PRO_FAT,
    itf.CD_REG_FAT,
    itf.CD_PRESTADOR,
    itf.CD_ATI_MED,
    itf.CD_LANCAMENTO,
    itf.CD_GRU_FAT,
    itf.CD_PROCEDIMENTO,
    itf.DT_PRODUCAO,
    itf.DT_LANCAMENTO AS DT_ITREG_FAT,
    itf.SN_REPASSADO,
    itf.SN_PERTENCE_PACOTE,
    itf.VL_UNITARIO,
    itf.VL_SP,
    itf.VL_ATO,
    itf.VL_TOTAL_CONTA,
    itf.VL_BASE_REPASSADO
FROM DBAMV.ITREG_FAT itf
WHERE (itf.SN_REPASSADO IN ('S', 'N') OR itf.SN_REPASSADO IS NULL) AND itf.DT_LANCAMENTO >= ADD_MONTHS(TRUNC(TO_DATE( ':PARAM' , 'YYYY-MM-DD')), -6)