SELECT
    TRIM(pf.CD_PRO_FAT) AS CD_PRO_FAT,
    pf.CD_GRU_PRO,
    pf.DS_PRO_FAT
FROM DBAMV.PRO_FAT pf
WHERE NOT REGEXP_LIKE(pf.CD_PRO_FAT, '^\d+$') AND TRIM(pf.CD_PRO_FAT) = 'X0000000'
UNION ALL
SELECT
    TRIM(pf.CD_PRO_FAT) AS CD_PRO_FAT,
    pf.CD_GRU_PRO,
    pf.DS_PRO_FAT
FROM DBAMV.PRO_FAT pf
WHERE REGEXP_LIKE(pf.CD_PRO_FAT, '^\d+$') AND TO_NUMBER(TRIM(pf.CD_PRO_FAT)) >= :PARAM