SELECT
    ra.CD_REG_AMB,
    ra.CD_REMESSA,
    ra.DT_LANCAMENTO AS DT_REG_AMB,
    ra.DT_REMESSA
FROM DBAMV.REG_AMB ra
WHERE ra.DT_LANCAMENTO >= ADD_MONTHS(TRUNC(TO_DATE( ':PARAM' , 'YYYY-MM-DD')), -6)