SELECT
    rf.CD_REG_FAT,
    rf.CD_CONVENIO,
    rf.CD_ATENDIMENTO,
    rf.CD_REMESSA,
    rf.DT_INICIO AS DT_REG_FAT,
    rf.DT_REMESSA
FROM DBAMV.REG_FAT rf
WHERE rf.DT_INICIO >= ADD_MONTHS(TRUNC(TO_DATE( ':PARAM' , 'YYYY-MM-DD')), -6)